[package]
name = "example"
version = "0.0.1"

[dependencies]
MoveStdlib = { git = "https://github.com/zkmove/aptos-core.git", subdir = "third_party/move/move-stdlib", rev = "witnessing" }

[addresses]
std = "0x1"

[circuit.fibonacci]
max_execution_rows = 278     # max rows of execution subcircuit
max_poseidon_rows = 100      # max rows of poseidon subcircuit
entry = { module_id = "0x1::fibonacci", function_name = "test_fibonacci" }

[circuit.zkhash_example]
max_poseidon_rows = 100
entry = { module_id = "0x1::zkhash_example", function_name = "hash" }