site_name: zkMove Docs
site_description: Documentation for zkMove
site_url: https://zkmove.github.io/zkmove/
repo_url: https://github.com/zkmove/zkmove
repo_name: zkmove

theme:
  name: material

plugins:
  - search

nav:
  - Home: index.md
  - Introduction:
      - A ZKVM for Programmable Privacy: introduction/zkvm-for-programmable-privacy.md
      - The Architecture: introduction/architecture.md
      - Why Move: introduction/why-move.md
  - Developer Document:
      - Set Up the Development Environment: developer/setup-dev-environment.md
      - Circuit and Proof: developer/circuit-and-proof.md
      - Deploy an On-Chain Verifier: developer/deploy-on-chain-verifier.md
      - Verify a Proof On-Chain: developer/verify-proof-on-chain.md
  - Circuit Design:
      - Circuit layout: inside-zkmove/circuit-layout.md
      - Memory consistency checking: inside-zkmove/memory-consistency-checking.md
      - Value representation: inside-zkmove/value-representation.md

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - tables
  - pymdownx.highlight
  - pymdownx.superfences
