site_name: zkMove Docs
site_description: Documentation for zkMove
site_url: https://zkmove.github.io/zkmove/
repo_url: https://github.com/zkmove/zkmove
repo_name: zkmove

theme:
  name: material

plugins:
  - search

nav:
  - Home: index.md
  - Introduction:
  - User Document:
      - Set Up the Development Environment: user/setup-dev-environment.md
      - Circuit and Proof: user/circuit-and-proof.md
      - Deploy an On-Chain Verifier: user/deploy-on-chain-verifier.md
      - Verify a Proof On-Chain: user/verify-proof-on-chain.md

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - tables
  - pymdownx.highlight
  - pymdownx.superfences
