use move_binary_format::file_format_common::Opcodes;
use strum_macros::EnumIter;
#[derive(Copy, Clone, Debug, PartialEq, Hash, Eq, Ord, PartialOrd, EnumIter)]
pub enum ExecutionState {
    Start = 0,
    ProcessArg,
    Teardown,
    Abort,
    ErrorState,
    AddSub,
    BrTrue,
    BrFalse,
    Bitwise,
    BitwiseStage1,
    BitwiseStage2,
    Branch,
    VecSwapStage1,
    VecSwapStage2,
    VecSwapStage3,
    VecSwapStage4,
    VecSwapStage5,
    VecPopBackStage1,
    VecPopBackStage2,
    VecPushBackStage1,
    VecPushBackStage2,
    Stop,
    Nop,
    BorrowLoc,
    LdConst,
    LdFalse,
    LdTrue,
    LdSimple,
    Pack,
    UnpackStage1,
    UnpackStage2,
    VecPack,
    VecUnpackStage1,
    VecUnpackStage2,
    ReadRef,
    BorrowField,
    WriteRefStage1,
    WriteRefStage2,
    WriteRefStage3,
    VecLen,
    VecBorrow,
    Pop,
    Cast,
    AndOr,
    Not,
    MoveLoc,
    CopyLoc,
    StoreLocStage1,
    StoreLocStage2,
    CallStage1,
    CallStage2,
    CallStage3,
    Ret,
    EqStage1,
    EqStage2,
    NeqStage1,
    NeqStage2,
    MulDivModStage1,
    MulDivModStage2,
    Le,
    Gt,
    Lt,
    Ge,
    ShiftStage1,
    ShiftStage2,
}

impl ExecutionState {
    pub const fn responsible_opcodes(&self) -> &[Opcodes] {
        match self {
            Self::Start => &[],
            Self::ProcessArg => &[],
            Self::Teardown => &[],
            Self::Stop => &[],
            Self::ErrorState => &[],
            Self::Abort => &[Opcodes::ABORT],
            Self::AddSub => &[Opcodes::ADD, Opcodes::SUB],
            Self::BrTrue => &[Opcodes::BR_TRUE],
            Self::BrFalse => &[Opcodes::BR_FALSE],
            Self::Bitwise | Self::BitwiseStage1 | Self::BitwiseStage2 => {
                &[Opcodes::BIT_AND, Opcodes::BIT_OR, Opcodes::XOR]
            }

            Self::Branch => &[Opcodes::BRANCH],
            Self::VecSwapStage1 => &[Opcodes::VEC_SWAP],
            Self::VecSwapStage2 => &[Opcodes::VEC_SWAP],
            Self::VecSwapStage3 => &[Opcodes::VEC_SWAP],
            Self::VecSwapStage4 => &[Opcodes::VEC_SWAP],
            Self::VecSwapStage5 => &[Opcodes::VEC_SWAP],
            Self::VecPopBackStage1 => &[Opcodes::VEC_POP_BACK],
            Self::VecPopBackStage2 => &[Opcodes::VEC_POP_BACK],
            Self::VecPushBackStage1 => &[Opcodes::VEC_PUSH_BACK],
            Self::VecPushBackStage2 => &[Opcodes::VEC_PUSH_BACK],
            Self::Nop => &[Opcodes::NOP],
            Self::BorrowLoc => &[Opcodes::IMM_BORROW_LOC, Opcodes::MUT_BORROW_LOC],
            Self::LdConst => &[Opcodes::LD_CONST],
            Self::LdFalse => &[Opcodes::LD_FALSE],
            Self::LdTrue => &[Opcodes::LD_TRUE],
            Self::LdSimple => &[
                Opcodes::LD_U8,
                Opcodes::LD_U16,
                Opcodes::LD_U32,
                Opcodes::LD_U64,
                Opcodes::LD_U128,
                Opcodes::LD_U256,
            ],
            Self::Pack => &[Opcodes::PACK],
            Self::UnpackStage1 => &[Opcodes::UNPACK],
            Self::UnpackStage2 => &[Opcodes::UNPACK, Opcodes::VEC_UNPACK],
            Self::VecPack => &[Opcodes::VEC_PACK],
            Self::VecUnpackStage1 => &[Opcodes::VEC_UNPACK],
            Self::VecUnpackStage2 => &[Opcodes::VEC_UNPACK],
            Self::ReadRef => &[Opcodes::READ_REF],
            Self::BorrowField => &[Opcodes::IMM_BORROW_FIELD, Opcodes::MUT_BORROW_FIELD],
            Self::WriteRefStage1 => &[Opcodes::WRITE_REF],
            Self::WriteRefStage2 => &[Opcodes::WRITE_REF],
            Self::WriteRefStage3 => &[Opcodes::WRITE_REF],
            Self::VecLen => &[Opcodes::VEC_LEN],
            Self::VecBorrow => &[Opcodes::VEC_IMM_BORROW, Opcodes::VEC_MUT_BORROW],
            Self::Pop => &[Opcodes::POP],
            Self::Cast => &[
                Opcodes::CAST_U8,
                Opcodes::CAST_U16,
                Opcodes::CAST_U32,
                Opcodes::CAST_U64,
                Opcodes::CAST_U128,
                Opcodes::CAST_U256,
            ],
            Self::AndOr => &[Opcodes::AND, Opcodes::OR],
            Self::Not => &[Opcodes::NOT],
            Self::MoveLoc => &[Opcodes::MOVE_LOC],
            Self::CopyLoc => &[Opcodes::COPY_LOC],
            Self::StoreLocStage1 => &[Opcodes::ST_LOC],
            Self::StoreLocStage2 => &[Opcodes::ST_LOC],
            Self::CallStage1 => &[Opcodes::CALL],
            Self::CallStage2 => &[Opcodes::CALL],
            Self::CallStage3 => &[Opcodes::CALL],
            Self::Ret => &[Opcodes::RET],
            Self::EqStage1 => &[Opcodes::EQ],
            Self::EqStage2 => &[Opcodes::EQ],
            Self::NeqStage1 => &[Opcodes::NEQ],
            Self::NeqStage2 => &[Opcodes::NEQ],
            Self::MulDivModStage1 => &[Opcodes::MUL, Opcodes::DIV, Opcodes::MOD],
            Self::MulDivModStage2 => &[Opcodes::MUL, Opcodes::DIV, Opcodes::MOD],
            Self::Le => &[Opcodes::LE],
            Self::Gt => &[Opcodes::GT],
            Self::Lt => &[Opcodes::LT],
            Self::Ge => &[Opcodes::GE],
            Self::ShiftStage1 => &[Opcodes::SHL, Opcodes::SHR],
            Self::ShiftStage2 => &[Opcodes::SHL, Opcodes::SHR],
        }
    }
}
