[package]
name = "confidential_asset"
version = "0.0.1"

[dependencies]
MoveStdlib = { git = "https://github.com/zkmove/aptos-core.git", subdir = "third_party/move/move-stdlib", rev = "witnessing" }

[addresses]
std = "0x1"
confidential_asset = "0x2"

verifier_api = "0x2bb0f19bf4970dad5e672ebe3f8cd30ff30b23736d567bf255c5eeadba064421"
param_address = "0xba8f59e3d5f949bc906e7c763e88c42f878af3aa2056fa3e51e61b61176bc986"
circuit_address = "0xba8f59e3d5f949bc906e7c763e88c42f878af3aa2056fa3e51e61b61176bc986"

[circuit]
max_poseidon_rows = 100
entry = { module_id = "0x2::off_chain", function_name = "encrypt" }

