// Copyright (c) zkMove Authors
use move_binary_format::file_format::Bytecode;
use std::fmt::Display;

// supported opcode
#[derive(Copy, Clone, Debug, PartialEq, Hash, Eq)]
pub enum Opcode {
    LdU8 = 0,
    LdU64,
    LdU128,
    LdConst,
    CastU8,
    CastU64,
    CastU128,
    Pop,
    Ret,
    Add,
    Mul,
    CopyLoc,
    Sub,
    Div,
    Mod,
    LdTrue,
    LdFalse,
    Eq,
    Neq,
    Shl,
    Shr,
    BitAnd,
    BitOr,
    Xor,
    And,
    Or,
    Not,
    MoveLoc,
    StLoc,
    Branch,
    BrTrue,
    BrFalse,
    Call,
    Abort,
    Le,
    Lt,
    Ge,
    Gt,
    Pack,
    Unpack,
    MutBorrowLoc,
    ImmBorrowLoc,
    ReadRef,
    WriteRef,
    FreezeRef,
    ImmBorrowField,
    MutBorrowField,
    MoveFrom,
    MoveTo,
    Exists,
    ImmBorrowGlobal,
    MutBorrowGlobal,
    CallGeneric,
    ImmBorrowGlobalGeneric,
    MutBorrowGlobalGeneric,
    ExistsGeneric,
    MoveFromGeneric,
    MoveToGeneric,
    PackGeneric,
    UnpackGeneric,
    ImmBorrowFieldGeneric,
    MutBorrowFieldGeneric,
    VecImmBorrow,
    VecMutBorrow,
    VecLen,
    VecPack,
    VecPopBack,
    VecPushBack,
    VecSwap,
    VecUnpack,
    Stop,
    Nop,
}

impl Default for Opcode {
    fn default() -> Self {
        Self::Nop
    }
}

impl Display for Opcode {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{:?}", self)
    }
}

impl Opcode {
    pub fn index(&self) -> usize {
        *self as usize
    }

    pub fn iter() -> impl Iterator<Item = Self> {
        [
            Self::LdU8,
            Self::LdU64,
            Self::LdU128,
            Self::LdConst,
            Self::CastU8,
            Self::CastU64,
            Self::CastU128,
            Self::Pop,
            Self::Ret,
            Self::Add,
            Self::Mul,
            Self::CopyLoc,
            Self::Sub,
            Self::Div,
            Self::Mod,
            Self::LdTrue,
            Self::LdFalse,
            Self::Eq,
            Self::Neq,
            Self::Shl,
            Self::Shr,
            Self::BitAnd,
            Self::BitOr,
            Self::Xor,
            Self::And,
            Self::Or,
            Self::Not,
            Self::MoveLoc,
            Self::StLoc,
            Self::Branch,
            Self::BrTrue,
            Self::BrFalse,
            Self::Call,
            Self::Abort,
            Self::Le,
            Self::Lt,
            Self::Ge,
            Self::Gt,
            Self::Pack,
            Self::Unpack,
            Self::MutBorrowLoc,
            Self::ImmBorrowLoc,
            Self::ReadRef,
            Self::WriteRef,
            Self::FreezeRef,
            Self::ImmBorrowField,
            Self::MutBorrowField,
            Self::MoveFrom,
            Self::MoveTo,
            Self::Exists,
            Self::ImmBorrowGlobal,
            Self::MutBorrowGlobal,
            Self::CallGeneric,
            Self::ImmBorrowGlobalGeneric,
            Self::MutBorrowGlobalGeneric,
            Self::ExistsGeneric,
            Self::MoveFromGeneric,
            Self::MoveToGeneric,
            Self::PackGeneric,
            Self::UnpackGeneric,
            Self::ImmBorrowFieldGeneric,
            Self::MutBorrowFieldGeneric,
            Self::VecImmBorrow,
            Self::VecMutBorrow,
            Self::VecLen,
            Self::VecPack,
            Self::VecPopBack,
            Self::VecPushBack,
            Self::VecSwap,
            Self::VecUnpack,
            Self::Stop,
            Self::Nop,
        ]
        .iter()
        .copied()
    }

    // pub(crate) const fn as_u64(&self) -> u64 {
    //     *self as u64
    // }

    pub fn total_numbers() -> usize {
        Self::iter().count()
    }
}

impl From<Bytecode> for Opcode {
    fn from(bytecode: Bytecode) -> Opcode {
        match bytecode {
            Bytecode::LdU8(_) => Opcode::LdU8,
            Bytecode::LdU64(_) => Opcode::LdU64,
            Bytecode::LdU128(_) => Opcode::LdU128,
            Bytecode::LdConst(_) => Opcode::LdConst,
            Bytecode::CastU8 => Opcode::CastU8,
            Bytecode::CastU64 => Opcode::CastU64,
            Bytecode::CastU128 => Opcode::CastU128,
            Bytecode::Pop => Opcode::Pop,
            Bytecode::Ret => Opcode::Ret,
            Bytecode::Add => Opcode::Add,
            Bytecode::Mul => Opcode::Mul,
            Bytecode::CopyLoc(_) => Opcode::CopyLoc,
            Bytecode::Sub => Opcode::Sub,
            Bytecode::Div => Opcode::Div,
            Bytecode::Mod => Opcode::Mod,
            Bytecode::LdTrue => Opcode::LdTrue,
            Bytecode::LdFalse => Opcode::LdFalse,
            Bytecode::Eq => Opcode::Eq,
            Bytecode::Neq => Opcode::Neq,
            Bytecode::Shl => Opcode::Shl,
            Bytecode::Shr => Opcode::Shr,
            Bytecode::BitAnd => Opcode::BitAnd,
            Bytecode::BitOr => Opcode::BitOr,
            Bytecode::Xor => Opcode::Xor,
            Bytecode::And => Opcode::And,
            Bytecode::Or => Opcode::Or,
            Bytecode::Not => Opcode::Not,
            Bytecode::MoveLoc(_) => Opcode::MoveLoc,
            Bytecode::StLoc(_) => Opcode::StLoc,
            Bytecode::Branch(_) => Opcode::Branch,
            Bytecode::BrTrue(_) => Opcode::BrTrue,
            Bytecode::BrFalse(_) => Opcode::BrFalse,
            Bytecode::Call(_) => Opcode::Call,
            Bytecode::Abort => Opcode::Abort,
            Bytecode::Le => Opcode::Le,
            Bytecode::Lt => Opcode::Lt,
            Bytecode::Ge => Opcode::Ge,
            Bytecode::Gt => Opcode::Gt,
            Bytecode::Pack(_) => Opcode::Pack,
            Bytecode::Unpack(_) => Opcode::Unpack,
            Bytecode::MutBorrowLoc(_) => Opcode::MutBorrowLoc,
            Bytecode::ImmBorrowLoc(_) => Opcode::ImmBorrowLoc,
            Bytecode::ReadRef => Opcode::ReadRef,
            Bytecode::WriteRef => Opcode::WriteRef,
            Bytecode::FreezeRef => Opcode::FreezeRef,
            Bytecode::ImmBorrowField(_) => Opcode::ImmBorrowField,
            Bytecode::MutBorrowField(_) => Opcode::MutBorrowField,
            Bytecode::MoveFrom(_) => Opcode::MoveFrom,
            Bytecode::MoveTo(_) => Opcode::MoveTo,
            Bytecode::Exists(_) => Opcode::Exists,
            Bytecode::ImmBorrowGlobal(_) => Opcode::ImmBorrowGlobal,
            Bytecode::MutBorrowGlobal(_) => Opcode::MutBorrowGlobal,
            Bytecode::CallGeneric(_) => Opcode::CallGeneric,
            Bytecode::ImmBorrowGlobalGeneric(_) => Opcode::ImmBorrowGlobalGeneric,
            Bytecode::MutBorrowGlobalGeneric(_) => Opcode::MutBorrowGlobalGeneric,
            Bytecode::ExistsGeneric(_) => Opcode::ExistsGeneric,
            Bytecode::MoveFromGeneric(_) => Opcode::MoveFromGeneric,
            Bytecode::MoveToGeneric(_) => Opcode::MoveToGeneric,
            Bytecode::PackGeneric(_) => Opcode::PackGeneric,
            Bytecode::UnpackGeneric(_) => Opcode::UnpackGeneric,
            Bytecode::ImmBorrowFieldGeneric(_) => Opcode::ImmBorrowFieldGeneric,
            Bytecode::MutBorrowFieldGeneric(_) => Opcode::MutBorrowFieldGeneric,
            Bytecode::VecImmBorrow(_) => Opcode::VecImmBorrow,
            Bytecode::VecMutBorrow(_) => Opcode::VecMutBorrow,
            Bytecode::VecLen(_) => Opcode::VecLen,
            Bytecode::VecPack(_, _) => Opcode::VecPack,
            Bytecode::VecPopBack(_) => Opcode::VecPopBack,
            Bytecode::VecPushBack(_) => Opcode::VecPushBack,
            Bytecode::VecSwap(_) => Opcode::VecSwap,
            Bytecode::VecUnpack(_, _) => Opcode::VecUnpack,
            // Bytecode::Stop(_) => Opcode::Stop,
            Bytecode::Nop => Opcode::Nop,
            _ => todo!(),
        }
    }
}
