// Copyright (c) zkMove Authors
use move_binary_format::file_format::Bytecode;
use std::fmt::Display;

//TODO: use Move opcodes directly

// supported opcode
#[derive(Copy, Clone, Debug, PartialEq, Hash, Eq)]
pub enum Opcode {
    Pop = 0x01,
    Ret = 0x02,
    BrTrue = 0x03,
    BrFalse = 0x04,
    Branch = 0x05,
    LdU64 = 0x06,
    LdConst = 0x07,
    LdTrue = 0x08,
    LdFalse = 0x09,
    CopyLoc = 0x0A,
    MoveLoc = 0x0B,
    StLoc = 0x0C,
    MutBorrowLoc = 0x0D,
    ImmBorrowLoc = 0x0E,
    MutBorrowField = 0x0F,
    ImmBorrowField = 0x10,
    Call = 0x11,
    Pack = 0x12,
    Unpack = 0x13,
    ReadRef = 0x14,
    WriteRef = 0x15,
    Add = 0x16,
    Sub = 0x17,
    Mul = 0x18,
    Mod = 0x19,
    Div = 0x1A,
    BitOr = 0x1B,
    BitAnd = 0x1C,
    Xor = 0x1D,
    Or = 0x1E,
    And = 0x1F,
    Not = 0x20,
    Eq = 0x21,
    Neq = 0x22,
    Lt = 0x23,
    Gt = 0x24,
    Le = 0x25,
    Ge = 0x26,
    Abort = 0x27,
    Nop = 0x28,
    Exists = 0x29,
    ImmBorrowGlobal = 0x2A,
    MutBorrowGlobal = 0x2B,
    MoveFrom = 0x2C,
    MoveTo = 0x2D,
    FreezeRef = 0x2E,
    Shl = 0x2F,
    Shr = 0x30,
    LdU8 = 0x31,
    LdU128 = 0x32,
    CastU8 = 0x33,
    CastU64 = 0x34,
    CastU128 = 0x35,
    MutBorrowFieldGeneric = 0x36,
    ImmBorrowFieldGeneric = 0x37,
    CallGeneric = 0x38,
    PackGeneric = 0x39,
    UnpackGeneric = 0x3A,
    ExistsGeneric = 0x3B,
    MutBorrowGlobalGeneric = 0x3C,
    ImmBorrowGlobalGeneric = 0x3D,
    MoveFromGeneric = 0x3E,
    MoveToGeneric = 0x3F,
    VecPack = 0x40,
    VecLen = 0x41,
    VecImmBorrow = 0x42,
    VecMutBorrow = 0x43,
    VecPushBack = 0x44,
    VecPopBack = 0x45,
    VecUnpack = 0x46,
    VecSwap = 0x47,
    LdU16 = 0x48,
    LdU32 = 0x49,
    LdU256 = 0x4A,
    CastU16 = 0x4B,
    CastU32 = 0x4C,
    CastU256 = 0x4D,
    Stop = 0x4E,
    Start = 0x4F,
}

impl Default for Opcode {
    fn default() -> Self {
        Self::Nop
    }
}

impl Display for Opcode {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{:?}", self)
    }
}

impl Opcode {
    pub fn index(&self) -> usize {
        *self as usize
    }

    pub fn iter() -> impl Iterator<Item = Self> {
        [
            Self::LdU8,
            Self::LdU16,
            Self::LdU32,
            Self::LdU64,
            Self::LdU128,
            Self::LdU256,
            Self::LdConst,
            Self::CastU8,
            Self::CastU16,
            Self::CastU32,
            Self::CastU64,
            Self::CastU128,
            Self::CastU256,
            Self::Pop,
            Self::Ret,
            Self::Add,
            Self::Mul,
            Self::CopyLoc,
            Self::Sub,
            Self::Div,
            Self::Mod,
            Self::LdTrue,
            Self::LdFalse,
            Self::Eq,
            Self::Neq,
            Self::Shl,
            Self::Shr,
            Self::BitAnd,
            Self::BitOr,
            Self::Xor,
            Self::And,
            Self::Or,
            Self::Not,
            Self::MoveLoc,
            Self::StLoc,
            Self::Branch,
            Self::BrTrue,
            Self::BrFalse,
            Self::Call,
            Self::Abort,
            Self::Le,
            Self::Lt,
            Self::Ge,
            Self::Gt,
            Self::Pack,
            Self::Unpack,
            Self::MutBorrowLoc,
            Self::ImmBorrowLoc,
            Self::ReadRef,
            Self::WriteRef,
            Self::FreezeRef,
            Self::ImmBorrowField,
            Self::MutBorrowField,
            Self::MoveFrom,
            Self::MoveTo,
            Self::Exists,
            Self::ImmBorrowGlobal,
            Self::MutBorrowGlobal,
            Self::CallGeneric,
            Self::ImmBorrowGlobalGeneric,
            Self::MutBorrowGlobalGeneric,
            Self::ExistsGeneric,
            Self::MoveFromGeneric,
            Self::MoveToGeneric,
            Self::PackGeneric,
            Self::UnpackGeneric,
            Self::ImmBorrowFieldGeneric,
            Self::MutBorrowFieldGeneric,
            Self::VecImmBorrow,
            Self::VecMutBorrow,
            Self::VecLen,
            Self::VecPack,
            Self::VecPopBack,
            Self::VecPushBack,
            Self::VecSwap,
            Self::VecUnpack,
            Self::Stop,
            Self::Nop,
        ]
        .iter()
        .copied()
    }

    // pub(crate) const fn as_u64(&self) -> u64 {
    //     *self as u64
    // }

    pub fn total_numbers() -> usize {
        Self::iter().count()
    }
}

impl From<Bytecode> for Opcode {
    fn from(bytecode: Bytecode) -> Opcode {
        match bytecode {
            Bytecode::LdU8(_) => Opcode::LdU8,
            Bytecode::LdU16(_) => Opcode::LdU16,
            Bytecode::LdU32(_) => Opcode::LdU32,
            Bytecode::LdU64(_) => Opcode::LdU64,
            Bytecode::LdU128(_) => Opcode::LdU128,
            Bytecode::LdU256(_) => Opcode::LdU256,
            Bytecode::LdConst(_) => Opcode::LdConst,
            Bytecode::CastU8 => Opcode::CastU8,
            Bytecode::CastU16 => Opcode::CastU16,
            Bytecode::CastU32 => Opcode::CastU32,
            Bytecode::CastU64 => Opcode::CastU64,
            Bytecode::CastU128 => Opcode::CastU128,
            Bytecode::CastU256 => Opcode::CastU256,
            Bytecode::Pop => Opcode::Pop,
            Bytecode::Ret => Opcode::Ret,
            Bytecode::Add => Opcode::Add,
            Bytecode::Mul => Opcode::Mul,
            Bytecode::CopyLoc(_) => Opcode::CopyLoc,
            Bytecode::Sub => Opcode::Sub,
            Bytecode::Div => Opcode::Div,
            Bytecode::Mod => Opcode::Mod,
            Bytecode::LdTrue => Opcode::LdTrue,
            Bytecode::LdFalse => Opcode::LdFalse,
            Bytecode::Eq => Opcode::Eq,
            Bytecode::Neq => Opcode::Neq,
            Bytecode::Shl => Opcode::Shl,
            Bytecode::Shr => Opcode::Shr,
            Bytecode::BitAnd => Opcode::BitAnd,
            Bytecode::BitOr => Opcode::BitOr,
            Bytecode::Xor => Opcode::Xor,
            Bytecode::And => Opcode::And,
            Bytecode::Or => Opcode::Or,
            Bytecode::Not => Opcode::Not,
            Bytecode::MoveLoc(_) => Opcode::MoveLoc,
            Bytecode::StLoc(_) => Opcode::StLoc,
            Bytecode::Branch(_) => Opcode::Branch,
            Bytecode::BrTrue(_) => Opcode::BrTrue,
            Bytecode::BrFalse(_) => Opcode::BrFalse,
            Bytecode::Call(_) => Opcode::Call,
            Bytecode::Abort => Opcode::Abort,
            Bytecode::Le => Opcode::Le,
            Bytecode::Lt => Opcode::Lt,
            Bytecode::Ge => Opcode::Ge,
            Bytecode::Gt => Opcode::Gt,
            Bytecode::Pack(_) => Opcode::Pack,
            Bytecode::Unpack(_) => Opcode::Unpack,
            Bytecode::MutBorrowLoc(_) => Opcode::MutBorrowLoc,
            Bytecode::ImmBorrowLoc(_) => Opcode::ImmBorrowLoc,
            Bytecode::ReadRef => Opcode::ReadRef,
            Bytecode::WriteRef => Opcode::WriteRef,
            Bytecode::FreezeRef => Opcode::FreezeRef,
            Bytecode::ImmBorrowField(_) => Opcode::ImmBorrowField,
            Bytecode::MutBorrowField(_) => Opcode::MutBorrowField,
            Bytecode::MoveFrom(_) => Opcode::MoveFrom,
            Bytecode::MoveTo(_) => Opcode::MoveTo,
            Bytecode::Exists(_) => Opcode::Exists,
            Bytecode::ImmBorrowGlobal(_) => Opcode::ImmBorrowGlobal,
            Bytecode::MutBorrowGlobal(_) => Opcode::MutBorrowGlobal,
            Bytecode::CallGeneric(_) => Opcode::CallGeneric,
            Bytecode::ImmBorrowGlobalGeneric(_) => Opcode::ImmBorrowGlobalGeneric,
            Bytecode::MutBorrowGlobalGeneric(_) => Opcode::MutBorrowGlobalGeneric,
            Bytecode::ExistsGeneric(_) => Opcode::ExistsGeneric,
            Bytecode::MoveFromGeneric(_) => Opcode::MoveFromGeneric,
            Bytecode::MoveToGeneric(_) => Opcode::MoveToGeneric,
            Bytecode::PackGeneric(_) => Opcode::PackGeneric,
            Bytecode::UnpackGeneric(_) => Opcode::UnpackGeneric,
            Bytecode::ImmBorrowFieldGeneric(_) => Opcode::ImmBorrowFieldGeneric,
            Bytecode::MutBorrowFieldGeneric(_) => Opcode::MutBorrowFieldGeneric,
            Bytecode::VecImmBorrow(_) => Opcode::VecImmBorrow,
            Bytecode::VecMutBorrow(_) => Opcode::VecMutBorrow,
            Bytecode::VecLen(_) => Opcode::VecLen,
            Bytecode::VecPack(_, _) => Opcode::VecPack,
            Bytecode::VecPopBack(_) => Opcode::VecPopBack,
            Bytecode::VecPushBack(_) => Opcode::VecPushBack,
            Bytecode::VecSwap(_) => Opcode::VecSwap,
            Bytecode::VecUnpack(_, _) => Opcode::VecUnpack,
            // Bytecode::Stop(_) => Opcode::Stop,
            Bytecode::Nop => Opcode::Nop,
            //_ => todo!(),
        }
    }
}
