name: CI checks

on:
  pull_request:
    types: [synchronize, opened, reopened, ready_for_review]
  push:
    branches:
      - main

#env:
#  RUSTFLAGS: "-D warnings"

## `actions-rs/toolchain@v1` overwrite set to false so that
## `rust-toolchain` is always used and the only source of truth.

jobs:
  test:
    if: github.event.pull_request.draft == false

    name: Test on ubuntu
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          override: false
      - name: Install Move CLI
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: --git https://github.com/zkmove/move move-cli --branch main
      - name: Generate witness
        working-directory: ./functional-tests
        run: |
          chmod +x ./gen_witness.sh
          ./gen_witness.sh
        shell: bash
      - name: Run tests with mock prover
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --features test-circuits --test testsuite -- test_all
      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --release --test testsuite -- test_all
#      - name: Check Benchmarks
#        uses: actions-rs/cargo@v1
#        with:
#          command: bench
#          args: --all --exclude functional-tests

  build:
    if: github.event.pull_request.draft == false

    name: Build target ${{ matrix.target }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          override: false
      - name: cargo build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --all-targets --workspace

  fmt:
    if: github.event.pull_request.draft == false

    name: Rustfmt
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          override: false
      - run: rustup component add rustfmt
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

  clippy:
    if: github.event.pull_request.draft == false

    name: Clippy lint checks
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          override: false
          components: clippy
      - name: Run clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --verbose --release --all --all-targets
